service: calc

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1
  environment:
    LIB_CALC: 'calc'

package:
  artifact: build/distributions/calc.zip

functions:
  calc:
    handler: com.serverless.Handler
    layers:
      - { Ref: CalculatorLambdaLayer }
    events:
      - http:
          path: calc
          method: post

layers:
  calculator:
    path: ../calculator-lib
    name: ${self:provider.stage}-calculator-layer
    description: Native library that implements a calculator
    compatibleRuntimes:
      - java8